### ISSUE TITLE
Hi, I use i5 9400 but no Graphic Card

### ISSUE THREAD

**Issue by anhqn94** [sumku404/ASUS-B365F-GAMING-Intel-9400F-AMD-RX580#1]
Can I use your EFI, or which I should to change in your EFI to use?

**Comment by 0x0501** [comment]
If your hardware is the same as mine, drop this to your EFI partition simply, and check if it works.

**Comment by anhqn94** [comment]
I tried it, but it doesn't work and my hardware not the same as you
B365f Rog Strix + i5 9400  that is all

**Comment by anhqn94** [comment]
I modified but it doesnt work too hmmm

**Comment by 0x0501** [comment]
Maybe you needa look through this tutorial [https://dortania.github.io/OpenCore-Install-Guide/installer-guide/opencore-efi.html](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/opencore-efi.html). I'm not really expert about this. The website has lots of guidance, on which I learnt how to build my EFI.
